on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azurecontaineringress.azurecr.io
        username: ${{ secrets.acr_azurecontaineringress_username }}
        password: ${{ secrets.acr_azurecontaineringress_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/COPY" -f  "ingress.yaml" -t azurecontaineringress.azurecr.io/aks:${{ github.sha }} --label dockerfile-path=ingress.yaml
        docker push azurecontaineringress.azurecr.io/aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep scriptest | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace scriptest`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: scriptest
        container-registry-url: azurecontaineringress.azurecr.io
        container-registry-username: ${{ secrets.acr_azurecontaineringress_username }}
        container-registry-password: ${{ secrets.acr_azurecontaineringress_password }}
        secret-name: aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: scriptest
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azurecontaineringress.azurecr.io/aks:${{ github.sha }}
        imagepullsecrets: |
          aksdockerauth
